# Generated by Django 5.1 on 2026-01-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0003_remove_employee_current_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Employee_ID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Employee_ID',
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
