# Generated by Django 5.1 on 2026-01-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_remove_employee_employee_id_remove_user_employee_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
