# Generated by Django 5.1 on 2026-01-22 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0005_rename_phone_number_employee_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_type',
        ),
    ]
