# Generated by Django 5.1 on 2026-01-23 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0006_remove_role_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAddressIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('identity_proof_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_number', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_document', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('identity_proof_type_2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_document_2', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeAddress',
        ),
    ]
