# Generated by Django 5.1 on 2026-02-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0010_alter_emailotp_created_at_alter_mobileotp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave'), ('Work From Home', 'Work From Home'), ('Half Day', 'Half Day')], default='Absent', max_length=20),
        ),
    ]
