# Generated by Django 5.1 on 2026-02-04 11:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0011_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='name',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Optional', 'Optional')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='paid_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='WorkFromHomeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Applied_date', models.DateField(verbose_name=django.utils.timezone.now)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('total_days', models.IntegerField()),
                ('reason', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('Regular', 'Regular'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Regular', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkFromHomeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approval', models.BooleanField(default=False)),
                ('manager_approval_status', models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='pending', max_length=20)),
                ('manager_approval_remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('manager_approval_date', models.DateField(auto_now_add=True)),
                ('hr_approval', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('WorkFromHomeRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.workfromhomerequest')),
            ],
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
