# Generated by Django 5.1 on 2026-02-04 12:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0012_remove_leavetype_name_leavetype_leave_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in_time',
            field=models.TimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out_time',
            field=models.TimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
    ]
