# Generated by Django 5.1 on 2026-02-04 14:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0013_alter_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workfromhomeapproval',
            old_name='WorkFromHomeRequest',
            new_name='wfh_request',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='hr_approval',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='manager_approval',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='manager_approval_date',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='manager_approval_remarks',
        ),
        migrations.RemoveField(
            model_name='workfromhomeapproval',
            name='manager_approval_status',
        ),
        migrations.AddField(
            model_name='workfromhomeapproval',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workfromhomeapproval',
            name='approved_date',
            field=models.DateTimeField(null=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='workfromhomeapproval',
            name='role',
            field=models.CharField(choices=[('MANAGER', 'Manager'), ('HR', 'HR')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workfromhomeapproval',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Approved', 'approved'), ('Rejected', 'rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workfromhomerequest',
            name='approval_type',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('SPECIAL', 'Special')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='workfromhomeapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workfromhomerequest',
            name='Applied_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workfromhomerequest',
            name='status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
