# Generated by Django 5.1 on 2026-02-05 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0014_rename_workfromhomerequest_workfromhomeapproval_wfh_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfromhomeapproval',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.role'),
        ),
    ]
