# Generated by Django 5.1 on 2026-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0015_alter_workfromhomeapproval_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfromhomerequest',
            name='status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
