# Generated by Django 5.1 on 2026-02-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0017_alter_workfromhomeapproval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workfromhomeapproval',
            name='approved_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
