# Generated by Django 5.1 on 2026-02-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0018_alter_workfromhomeapproval_approved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeaddressidentity',
            name='identity_proof_document',
            field=models.ImageField(blank=True, null=True, upload_to='identity_proofs/'),
        ),
        migrations.AlterField(
            model_name='employeeaddressidentity',
            name='identity_proof_document_2',
            field=models.ImageField(blank=True, null=True, upload_to='identity_proofs/'),
        ),
    ]
