# Generated by Django 5.1 on 2026-02-06 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0019_alter_employeeaddressidentity_identity_proof_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebalance',
            name='casual_leave_balance',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='optional_leave_balance',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='sick_leave_balance',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeaddressidentity',
            name='identity_proof_document',
            field=models.FileField(blank=True, null=True, upload_to='identity_proofs/'),
        ),
        migrations.AlterField(
            model_name='employeeaddressidentity',
            name='identity_proof_document_2',
            field=models.FileField(blank=True, null=True, upload_to='identity_proofs/'),
        ),
        migrations.AlterField(
            model_name='employeeaddressidentity',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='from_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='to_date',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Optional', 'Optional')], default='Optional', max_length=50),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='paid_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], default='UnPaid', max_length=10),
        ),
    ]
