# Generated by Django 5.1 on 2026-02-09 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0020_employeeleavebalance_casual_leave_balance_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeleavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeeleavebalance',
            name='compoff_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='optional_leave_balance',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Optional', 'Optional'), ('CompOff', 'CompOff')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='paid_type',
            field=models.CharField(choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10),
        ),
        migrations.CreateModel(
            name='EmployeeDetailesCheckBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures/')),
                ('identity_proof_type', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_number', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_document', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('identity_proof_type_2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_number_2', models.CharField(blank=True, max_length=100, null=True)),
                ('identity_proof_document_2', models.FileField(blank=True, null=True, upload_to='identity_proofs/')),
                ('hr_approval', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeleavebalance',
            name='leave_type',
        ),
    ]
