# Generated by Django 5.1 on 2026-02-09 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0021_alter_employeeleavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaveapplication',
            old_name='manager_approved',
            new_name='admin_approved',
        ),
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Optional', 'Optional'), ('CompOff', 'CompOff')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='paid_type',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10, null=True),
        ),
    ]
