# Generated by Django 5.1 on 2026-02-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0023_employee_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='address_line1',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='city',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='country',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_document',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_document_2',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_number',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_number_2',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_type',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='identity_proof_type_2',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='employeedetailescheckbox',
            name='state',
        ),
        migrations.AddField(
            model_name='employeedetailescheckbox',
            name='employee_data_for_approval',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
