# Generated by Django 5.1 on 2026-02-10 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0024_remove_employeedetailescheckbox_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_data_for_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employeedetailescheckbox'),
        ),
        migrations.AddField(
            model_name='employeeaddressidentity',
            name='employee_data_for_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employeedetailescheckbox'),
        ),
        migrations.AddField(
            model_name='employeeemergencycontact',
            name='employee_data_for_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employeedetailescheckbox'),
        ),
    ]
