# Generated by Django 5.1 on 2026-02-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0025_employee_employee_data_for_approval_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_data_for_approval',
        ),
        migrations.RemoveField(
            model_name='employeeaddressidentity',
            name='employee_data_for_approval',
        ),
        migrations.RemoveField(
            model_name='employeeemergencycontact',
            name='employee_data_for_approval',
        ),
        migrations.AddField(
            model_name='employeedetailescheckbox',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.employee'),
        ),
        migrations.AlterField(
            model_name='employeedetailescheckbox',
            name='hr_approval',
            field=models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('REJECTED', 'REJECTED')], default='PENDING', max_length=20),
        ),
    ]
