# Generated by Django 5.1 on 2026-02-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0026_remove_employee_employee_data_for_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('Casual', 'Casual'), ('Sick', 'Sick'), ('Optional', 'Optional'), ('CompOff', 'CompOff')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='half_day_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='paid_type',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('UnPaid', 'UnPaid')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='probation_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='to_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
