# Generated by Django 5.1 on 2026-02-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0027_alter_leaveapplication_leave_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.JSONField(blank=True, null=True)),
                ('optional_holiday', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaveapplication',
            name='admin_approved',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='manager_approved',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
