# Generated by Django 5.1 on 2026-02-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0028_holiday_remove_leaveapplication_admin_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='holiday',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'NATIONAL'), ('FESTIVAL', 'FESTIVAL'), ('COMPANY', 'COMPANY'), ('OPTIONAL', 'OPTIONAL')], max_length=50, null=True),
        ),
    ]
