# Generated by Django 5.1 on 2026-02-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0030_holiday_created_by_holiday_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebalance',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='type',
            field=models.CharField(blank=True, choices=[('NATIONAL', 'NATIONAL'), ('FESTIVAL', 'FESTIVAL'), ('COMPANY', 'COMPANY')], max_length=50, null=True),
        ),
    ]
